# SEO keywords and description for your site.
keywords = [
  "PowerShell",
  "DevOps",
  "IT Automation",
  "Cybersecurity",
  "Cloud Security",
  "Microsoft Sentinel",
  "Network Automation",
  "IT Infrastructure",
  "System Administration",
  "PowerShell Scripting",
]
subtitle = "PowerShell, DevOps, Security, and Automation Expert."

description = "Explore expert insights on PowerShell, DevOps, IT automation, cybersecurity, and cloud security by Saggie Haim. Learn how to streamline IT infrastructure, enhance system administration, and automate tasks with comprehensive guides and tutorials."

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "posts"

showReadingTime = true

[author]
  name = "Saggie Haim"
  email = "contact@saggiehaim.net"

[search]
  summaryInclude = 180 # show only part of content in search result.
  minMatchCharLength = 2 # https://www.fusejs.io/api/options.html#minmatchcharlength
  threshold = 0.3 # https://www.fusejs.io/api/options.html#threshold

[header]
  logo = "white_logo.png"
  sticky = true


[footer]
  since = 2018
  poweredby = false

[social_media]
  [[social_media.items]]
    enabled = true
    title = 'Linkedin'
    icon = 'brand-linkedin'
    link = 'https://www.linkedin.com/in/saggie/'

  [[social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/SaggehaimBlog'